import './globals.css'

import Header from '../../components/header/Header'
import Footer from '../../components/footer/Footer'
import { Questrial } from '@next/font/google'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const questrial = Questrial({
  subsets:['latin'],
  weight:['400']
})

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${questrial.className} bg-[url("../../public/Backgrounds.svg")] bg-cover bg-left-top `}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
